version: '3.8'
networks:
  ai_network:
    driver: bridge

services:
  heygem-f2f:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/guiji2025_heygem.ai
    container_name: heygem-f2f
    restart: always
    privileged: true
    volumes:
      - /data/models/heygem/data/face2face:/app/data/face2face
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: "nvidia"
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network
  f5-tts:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/f5-tts:heygem
    container_name: f5-tts
    restart: always
    privileged: true
    volumes:
      - /root/.cache/huggingface/hub:/root/.cache/huggingface/hub/
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: "nvidia"
    ports:
      - '7861:7861'
    networks:
      - ai_network
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - '3306:3306'
    volumes:
      - /data/models/heygem/data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  heygem-api:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/heygem-api:v0.0.2
    container_name: heygem-api
    restart: always
    privileged: true
    volumes:
      - ../config/config.docker.yaml:/app/config.yaml
      - /data/models/heygem/data/face2face:/app/resource/public
    ports:
      - '8000:8000'
    networks:
      - ai_network
