version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - '3306:3306'
    volumes:
      - D:/docker_data/mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
