// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"heygem-api/internal/dao/internal"
)

// internalContextDao is an internal type for wrapping the internal DAO implementation.
type internalContextDao = *internal.ContextDao

// contextDao is the data access object for the table context.
// You can define custom methods on it to extend its functionality as needed.
type contextDao struct {
	internalContextDao
}

var (
	// Context is a globally accessible object for table context operations.
	Context = contextDao{
		internal.NewContextDao(),
	}
)

// Add your custom methods and functionality below.
