// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"heygem-api/internal/dao/internal"
)

// internalModelDao is an internal type for wrapping the internal DAO implementation.
type internalModelDao = *internal.ModelDao

// modelDao is the data access object for the table model.
// You can define custom methods on it to extend its functionality as needed.
type modelDao struct {
	internalModelDao
}

var (
	// Model is a globally accessible object for table model operations.
	Model = modelDao{
		internal.NewModelDao(),
	}
)

// Add your custom methods and functionality below.
