// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"heygem-api/internal/dao/internal"
)

// internalVideoDao is an internal type for wrapping the internal DAO implementation.
type internalVideoDao = *internal.VideoDao

// videoDao is the data access object for the table video.
// You can define custom methods on it to extend its functionality as needed.
type videoDao struct {
	internalVideoDao
}

var (
	// Video is a globally accessible object for table video operations.
	Video = videoDao{
		internal.NewVideoDao(),
	}
)

// Add your custom methods and functionality below.
