// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"heygem-api/internal/dao/internal"
)

// internalVoiceDao is an internal type for wrapping the internal DAO implementation.
type internalVoiceDao = *internal.VoiceDao

// voiceDao is the data access object for the table voice.
// You can define custom methods on it to extend its functionality as needed.
type voiceDao struct {
	internalVoiceDao
}

var (
	// Voice is a globally accessible object for table voice operations.
	Voice = voiceDao{
		internal.NewVoiceDao(),
	}
)

// Add your custom methods and functionality below.
