// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package voice

import (
	"heygem-api/api/voice"
)

type ControllerV1 struct{}

func NewV1() voice.IVoiceV1 {
	return &ControllerV1{}
}
